version: "3.9"
services:
  web:
    image: odoo:17.0
    depends_on:
      - mydb
    ports:
      - "8236:8236"
    environment:
      DB_HOST: dpg-ctui5hlds78s73foc27g-a
      DB_USER: odoo17_fpft_user
      DB_PASSWORD: Grlvrz2SyJligOrJNPmivGV6hiwWDam9
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL to be ready...';
        COUNT=0;
        while ! pg_isready -h dpg-ctui5hlds78s73foc27g-a -p 5432 -U odoo17_fpft_user; do
          sleep 2;
          COUNT=$((COUNT+1));
          if [ $COUNT -ge 30 ]; then
            echo 'Timeout waiting for PostgreSQL. Exiting...';
            exit 1;
          fi;
        done;
        echo 'PostgreSQL is ready. Starting Odoo...';
        odoo -d odoo_17 -i base --db_host=dpg-ctui5hlds78s73foc27g-a --db_user=odoo17_fpft_user --db_password=Grlvrz2SyJligOrJNPmivGV6hiwWDam9 --without-demo=all
      "

    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
      - ./filestore:/var/lib/odoo/.local/share/Odoo/filestore
      - ./filestore/.local/share/Odoo/sessions:/var/lib/odoo/.local/share/Odoo/sessions

  mydb:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo17_fpft
      POSTGRES_USER: odoo17_fpft_user
      POSTGRES_PASSWORD: Grlvrz2SyJligOrJNPmivGV6hiwWDam9
    volumes:
      - mydb_data:/var/lib/postgresql/data

volumes:
  mydb_data:
