version: "3.9"
services:
  web:
    image: odoo:17.0
    depends_on:
      - mydb
    ports:
      - "8236:8069" # Map 8236 on the host to 8069 in the container
    environment:
      DB_HOST: mydb
      DB_USER: odoo17_fpft_user
      DB_PASSWORD: Grlvrz2SyJligOrJNPmivGV6hiwWDam9
      DB_NAME: odoo17_fpft
    command: /etc/odoo/inidb.sh
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
      - ./filestore:/var/lib/odoo/.local/share/Odoo/filestore
      - ./filestore/.local/share/Odoo/sessions:/var/lib/odoo/.local/share/Odoo/sessions

  mydb:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo17_fpft
      POSTGRES_USER: odoo17_fpft_user
      POSTGRES_PASSWORD: Grlvrz2SyJligOrJNPmivGV6hiwWDam9
    volumes:
      - mydb_data:/var/lib/postgresql/data

volumes:
  mydb_data:
