version: "3.9"
services:
  web:
    image: odoo:17.0
    depends_on:
      - mydb
    ports:
      - "8236:8236"
    environment:
      DB_HOST: mydb # Use the service name here (mydb)
      DB_USER: odoo17_fpft_user
      DB_PASSWORD: Grlvrz2SyJligOrJNPmivGV6hiwWDam9
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL to be ready...';
        COUNT=0;
        while ! pg_isready -h mydb -p 5432 -U odoo17_fpft_user; do  # Adjust to use service name
          sleep 2;
          COUNT=$((COUNT+1));
          if [ $COUNT -ge 30 ]; then
            echo 'Timeout waiting for PostgreSQL. Exiting...';
            exit 1;
          fi;
        done;
        echo 'PostgreSQL is ready. Starting Odoo...';
        odoo
      "
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
      - ./filestore:/var/lib/odoo/.local/share/Odoo/filestore
      - ./filestore/.local/share/Odoo/sessions:/var/lib/odoo/.local/share/Odoo/sessions

  mydb:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo17_fpft
      POSTGRES_USER: odoo17_fpft_user
      POSTGRES_PASSWORD: Grlvrz2SyJligOrJNPmivGV6hiwWDam9
    volumes:
      - mydb_data:/var/lib/postgresql/data

volumes:
  mydb_data:
